name: Ci packages

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - run: npm install
            - name: compile
              run: npm run lib
