name: Format code

on:
    pull_request:
        branches: ['main']

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - run: npm install
            - name: prettier
              run: npm run format
