name: format code

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            - run: npm install --frozen-lockfile --check-files
            - name: prettier
              run: npm run format:all
