name: Build packages

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - run: npm install
            - name: compile
              run: npm run lib:all
